### ISSUE TITLE
Support for similarly named Public and Private Hosted Zones

### ISSUE THREAD

**Issue by anthcourtney** [widdix/node-route53-updater#2]
I have a Private and a Public Hosted Zone which are named the same.

There appears to be no support for specifying a Zone ID (rather than a Hosted Zone Name) when performing an update, therefore the utility seems to update the first hosted zone that it finds. This could be the public one, or could be the private one. This behaviour is undesirable.

**Comment by andreaswittig** [comment]
Hi @anthcourtney, good point. 👍

**Comment by michaelwittig** [comment]
Thanks @anthcourtney 

I made two changes:
1. The tool fails if it finds more than one hosted zone with the provided `--hostedZoneName`
2. I added the parameter `--hostedZoneId` to specify the zone directly

Released as route53-updater@1.0.0

**Comment by anthcourtney** [comment]
This works perfectly. Thanks guys.
